spring:
  liquibase:
    enabled: true
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  application:
    name: music-service
  datasource:
    url: jdbc:postgresql://localhost:5438/spotik
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix:
    classpath: /templates/
    suffix: .html
    enabled: false
  storage:
    musicLocation: /music
    textLocation: /texts
  logging:
    level:
      org.springframework: TRACE